version: '3.7'

services:
  torrent-indexer:
    image: ghcr.io/ruizlenato/torrent-indexer:main
    container_name: torrent-indexer
    environment:
      - REDIS_HOST=redis
    ports:
      - 7006:7006
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped